kind: wasmer.io/App.v0
name: SiratPay
app_id: da_KGzIxtmU4NY1
owner: moparapairayat
package: .
env:
  DB_HOST: db.fr-pari1.bengt.wasmernet.com
  DB_PORT: '10272'
  DB_USERNAME: user_2809cae2
  DB_PASSWORD: pw_zkNMyT2l08HhGcJEa4faalj8rr3zTGuc
  DB_NAME: Siratpay
  DB_PREFIX: pp_
capabilities:
  instaboot:
    mode: null
